### ISSUE TITLE
Barplot improvements

### ISSUE THREAD

**Issue by agouy** [tercen/barplot_operator#1]
- [x] add themes
- [x] add color scales. default, same as Tercen + option for a different one
- [x] position_dodge to be customised
- [x] error when jitter but no color
- [x] error when "+" sign in row or column names (R formula conflict)
- [x] customise nrow or ncol when single row / column

**Comment by agouy** [comment]
@makostadima FYI this is the issue for barplot improvements

**Comment by agouy** [comment]
@makostadima Barplot v 0.1.0 is ready to be tested

**Comment by makostadima** [comment]
Great news! I will be testing soon and let you know.

**Comment by makostadima** [comment]
So I came across an error, which I am not sure if it because I added 2 factors on colors:

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/1746464/178519040-6857c2d8-5511-4abc-af23-2cace16974de.png">

Here's the data step: https://tercen.com/test-team/w/3d0482ed7ae6c2f2d24e5678cd5af239/ds/ebda5081-aae4-45fc-b91b-f7b4b19d402a

**Comment by makostadima** [comment]
Check also this step: https://tercen.com/test-team/w/3d0482ed7ae6c2f2d24e5678cd5af239/ds/bbca4146-337c-468f-be93-280d29849c1f/crosstab

What I get in the computed barplot isn't what I expected, as not every group contain two measurements in the resulting barplot and the y axis range is much smaller than it should.

In this example I have only one measurement per color group within each x-axis tick.

**Comment by agouy** [comment]
@makostadima v 0.1.1 support multiple color factors
